apiVersion: v1
kind: Pod
metadata:
    name: aggregator1011
spec:
    containers:
    - image: jaysonboubin/aggregator:latest
      name: aggregator1011
      command: ["bash"]
      args: ["run.sh"]
      env:
      - name: Models
        value: "1011"
      - name: HDFS
        value: "184.57.4.230"
