apiVersion: v1
kind: Pod
metadata:
    name: aggregator1110
spec:
    containers:
    - image: jaysonboubin/aggregator:latest
      name: aggregator1110
      command: ["bash"]
      args: ["run.sh"]
      volumeMounts:
      - mountPath: /home/mydata
        name: mydata
      env:
      - name: Models
        value: "1110"
      - name: HDFS
        value: "10.0.0.6"
    volumes:
    - name: mydata
      hostPath:
        path: /host/Data/
