apiVersion: v1
kind: Pod
metadata:
    name: aggregator1100
spec:
    containers:
    - image: jaysonboubin/aggregator:latest
      name: aggregator1100
      command: ["bash"]
      args: ["run.sh"]
      env:
      - name: Models
        value: "1100"
      - name: HDFS
        value: "184.57.4.230"
