apiVersion: v1
kind: Pod
metadata:
    name: aggregator1101
spec:
    containers:
    - image: jaysonboubin/aggregator:latest
      name: aggregator1101
      command: ["bash"]
      args: ["run.sh"]
      env:
      - name: Models
        value: "1101"
      - name: HDFS
        value: "184.57.4.230"
