apiVersion: v1
kind: Pod
metadata:
    name: worker11
spec:
    containers:
    - image: jaysonboubin/worker:latest
      name: worker11
      command: ["bash"]
      args: ["run.sh"]
      volumeMounts:
      - mountPath: /home/mydata
        name: mydata
      env:
      - name: SERVERNUM
        value: "1"
      - name: WORKERNUM
        value: "1"
      - name: HDFS
        value: "10.0.0.6"
    volumes:
    - name: mydata
      hostPath:
        path: /host/Data/Worker1_1
