apiVersion: v1
kind: Pod
metadata:
    name: worker00
spec:
    containers:
    - image: jaysonboubin/worker:latest
      name: worker00
      command: ["bash"]
      args: ["run.sh"]
      env:
      - name: SERVERNUM
        value: "0"
      - name: WORKERNUM
        value: "0"
      - name: HDFS
        value: "184.57.4.230"
